export default {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-0": "var(--primary-0)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        brand: {
          DEFAULT: "var(--brand-ember)",
          foreground: "var(--brand-ember-foreground)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Global text colors
        "text-heading": "var(--text-heading)",
        "text-menu-active": "var(--text-menu-active)",
        "text-menu-hover": "var(--text-menu-hover)",
        "text-normal": "var(--text-normal)",
        "bg-transparent": "var(--bg-transparent)",
        
        // Theme Background Colors
        "bg-primary": "var(--bg-primary)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-card": "var(--bg-card)",
        "bg-card-opacity": "var(--bg-card-opacity)",
        "bg-dark": "var(--bg-dark)",
        "bg-darker": "var(--bg-darker)",
        "bg-darkest": "var(--bg-darkest)",
        "bg-panel": "var(--bg-panel)",
        "bg-button": "var(--bg-button)",
        "bg-button-dark": "var(--bg-button-dark)",
        "bg-button-text": "var(--bg-button-text)",
        "bg-gray": "var(--bg-gray)",
        "bg-gray-light": "var(--bg-gray-light)",
        "bg-gray-medium": "var(--bg-gray-medium)",
        
        // Theme Text Colors
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-muted-light": "var(--text-muted-light)",
        "text-gray": "var(--text-gray)",
        "text-gray-light": "var(--text-gray-light)",
        "text-gray-medium": "var(--text-gray-medium)",
        "text-gray-lighter": "var(--text-gray-lighter)",
        "text-gray-lightest": "var(--text-gray-lightest)",
        "text-dark": "var(--text-dark)",
        "text-dark-medium": "var(--text-dark-medium)",
        "text-dark-light": "var(--text-dark-light)",
        
        // Theme Border Colors
        "border-primary": "var(--border-primary)",
        "border-secondary": "var(--border-secondary)",
        "border-light": "var(--border-light)",
        "border-medium": "var(--border-medium)",
        "border-white-10": "var(--border-white-10)",
        "border-white-05": "var(--border-white-05)",
        "border-white-08": "var(--border-white-08)",
        "border-white-05-hex": "var(--border-white-05-hex)",
        "border-white-0a": "var(--border-white-0a)",
        "border-white-0f": "var(--border-white-0f)",
        "border-white-26": "var(--border-white-26)",
        "border-white-1f": "var(--border-white-1f)",
        "border-gray": "var(--border-gray)",
        "border-gray-80": "var(--border-gray-80)",
        "border-gray-33": "var(--border-gray-33)",
        
        // Theme Accent Colors
        "accent-cyan": "var(--accent-cyan)",
        "accent-cyan-light": "var(--accent-cyan-light)",
        "accent-yellow": "var(--accent-yellow)",
        "accent-white": "var(--accent-white)",
        "accent-gray": "var(--accent-gray)",
        "accent-gray-light": "var(--accent-gray-light)",
        "accent-beige": "var(--accent-beige)",
        
        // Theme Shadow Colors
        "shadow-black-40": "var(--shadow-black-40)",
        "shadow-black-1f": "var(--shadow-black-1f)",
        "shadow-black-0a": "var(--shadow-black-0a)",
        "shadow-black-4c": "var(--shadow-black-4c)",
        "shadow-black-0d": "var(--shadow-black-0d)",
        "shadow-blue-1a": "var(--shadow-blue-1a)",
        "shadow-gray-0d": "var(--shadow-gray-0d)",
        "shadow-purple-1a": "var(--shadow-purple-1a)",
        "shadow-white-1a": "var(--shadow-white-1a)",
        "shadow-white-26": "var(--shadow-white-26)",
        "shadow-white-1c": "var(--shadow-white-1c)",
        "shadow-blue-08": "var(--shadow-blue-08)",
        
        // Theme Overlay Colors
        "overlay-white-05": "var(--overlay-white-05)",
        "overlay-white-08": "var(--overlay-white-08)",
        "overlay-white-10": "var(--overlay-white-10)",
        "overlay-white-15": "var(--overlay-white-15)",
        "overlay-white-20": "var(--overlay-white-20)",
        "overlay-white-26": "var(--overlay-white-26)",
        "overlay-white-40": "var(--overlay-white-40)",
        "overlay-white-60": "var(--overlay-white-60)",
        "overlay-white-80": "var(--overlay-white-80)",
        "overlay-white-95": "var(--overlay-white-95)",
        "overlay-black-05": "var(--overlay-black-05)",
        "overlay-black-10": "var(--overlay-black-10)",
        "overlay-black-20": "var(--overlay-black-20)",
        "overlay-black-30": "var(--overlay-black-30)",
        "overlay-black-40": "var(--overlay-black-40)",
        "overlay-black-50": "var(--overlay-black-50)",
        "overlay-gray-80": "var(--overlay-gray-80)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        "monte-carlo": ["var(--font-monte-carlo)", "cursive"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        pulse: "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
